"""empty message

Revision ID: 6f41aeccb54b
Revises: 72d383f3e4a5
Create Date: 2020-03-24 10:34:30.492663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f41aeccb54b'
down_revision = '72d383f3e4a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'description')
    # ### end Alembic commands ###
